[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["google-auth-library"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200